apiVersion: apps/v1
kind: Deployment
metadata:
  name: policygate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policygate
  template:
    metadata:
      labels:
        app: policygate
    spec:
      containers:
        - name: policygate
          image: policygate:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: policygate-config
            - secretRef:
                name: policygate-secret
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
