apiVersion: v1
kind: Secret
metadata:
  name: policygate-secret
type: Opaque
stringData:
  POSTGRES_USER: policygate
  POSTGRES_PASSWORD: policygate
  SPRING_DATASOURCE_USERNAME: policygate
  SPRING_DATASOURCE_PASSWORD: policygate
