CREATE TABLE rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    version INTEGER NOT NULL,
    expression VARCHAR(1000) NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_rules_name_version UNIQUE (name, version),
    CONSTRAINT ck_rules_version_positive CHECK (version >= 1)
);

CREATE UNIQUE INDEX uk_rules_active_name ON rules (name) WHERE active;
